export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT_START = 'LOGOUT_START'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'

export const LOAD_ROOMS_START = 'LOAD_ROOMS_START'
export const LOAD_ROOMS_SUCCESS = 'LOAD_ROOMS_SUCCESS'
export const LOAD_ROOMS_ERROR = 'LOAD_ROOMS_ERROR'

export const LOAD_ROOM_BY_ID_START = 'LOAD_ROOM_BY_ID_START'
export const LOAD_ROOM_BY_ID_SUCCESS = 'LOAD_ROOM_BY_ID_SUCCESS'
export const LOAD_ROOM_BY_ID_ERROR = 'LOAD_ROOM_BY_ID_ERROR'

export const CREATE_ROOM_START = 'CREATE_ROOM_START'
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS'
export const CREATE_ROOM_ERROR = 'CREATE_ROOM_ERROR'

export const DELETE_ROOM_START = 'DELETE_ROOM_START'
export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS'
export const DELETE_ROOM_ERROR = 'DELETE_ROOM_ERROR'

export const SET_STEP = "SET_STEP"
export const SET_ACTIVE_ROOM = 'SET_ACTIVE_ROOM'
export const SET_FILTERED_ROOMS = 'SET_FILTERED_ROOMS'
export const NEW_USERS_FOR_ROOM = 'NEW_USERS_FOR_ROOM'