export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT_START = 'LOGOUT_START'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'

export const LOAD_ROOMS_START = 'LOAD_ROOMS_START'
export const LOAD_ROOMS_SUCCESS = 'LOAD_ROOMS_SUCCESS'
export const LOAD_ROOMS_ERROR = 'LOAD_ROOMS_ERROR'

export const CREATE_ROOM_START = 'CREATE_ROOM_START'
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS'
export const CREATE_ROOM_ERROR = 'CREATE_ROOM_ERROR'

export const SET_STEP = "SET_STEP"
export const SET_ACTIVE_ROOM = 'SET_ACTIVE_ROOM'
export const SET_FILTERED_ROOMS = 'SET_FILTERED_ROOMS'