export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT_START = 'LOGOUT_START'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'

export const LOAD_CHATS_START = 'LOAD_CHATS_START'
export const LOAD_CHATS_SUCCESS = 'LOAD_CHATS_SUCCESS'
export const LOAD_CHATS_ERROR = 'LOAD_CHATS_ERROR'

export const CREATE_CHAT_START = 'CREATE_CHAT_START'
export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS'
export const CREATE_CHAT_ERROR = 'CREATE_CHAT_ERROR'

export const SET_STEP = "SET_STEP"
export const SET_CHATS = 'SET_CHATS'
export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT'
export const SET_FILTERED_CHATS = 'SET_FILTERED_CHATS'